# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Daftar Jurusan',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Daftar Kelas',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_siswa', models.IntegerField()),
                ('bulan_yang_dibayar', models.DateField()),
                ('nominal_yang_dibayar', models.IntegerField()),
                ('tanggal_pembayaran', models.DateField()),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bpp.Jurusan')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bpp.Kelas')),
            ],
            options={
                'verbose_name_plural': 'Daftar Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_siswa', to='app_bpp.Jurusan')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_siswa', to='app_bpp.Kelas')),
            ],
            options={
                'verbose_name_plural': 'Daftar Siswa',
            },
        ),
    ]
