# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bpp', '0002_auto_20200410_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='kelas',
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='id_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bpp.Siswa'),
        ),
    ]
