# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bpp', '0004_auto_20200410_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bpp.Siswa'),
        ),
    ]
